[package]
name = "raspi-collector"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "raspi-collector"
path = "src/main.rs"

[[bin]]
name = "simulate"
path = "src/simulate.rs"

[dependencies]
serialport = { version = "4.3", default-features = false }
log        = "0.4"
env_logger = "0.11"
serde      = { version = "1", features = ["derive"] }
serde_json = "1"
i2cdev     = "0.5"
rumqttc    = "0.24"
dotenvy    = "0.15"
clap       = { version = "4", features = ["derive"] }

[profile.release]
opt-level     = "z"
lto           = true
strip         = true
codegen-units = 1
